/**
 * Application Types
 * Central location for all TypeScript types and interfaces
 */

import type { IUser } from '../interfaces/IUser';

// ============================================
// API TYPES
// ============================================

/**
 * Standard API response wrapper
 */
export interface ApiResponse<T = any> {
  success: boolean;
  message: string;
  data?: T;
  error?: string;
}

/**
 * Pagination parameters
 */
export interface PaginationParams {
  page?: number;
  limit?: number;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
}

/**
 * Paginated response wrapper
 */
export interface PaginatedResponse<T> {
  success: boolean;
  message: string;
  data: T[];
  pagination: {
    currentPage: number;
    totalPages: number;
    totalItems: number;
    itemsPerPage: number;
  };
}

// ============================================
// USER TYPES
// ============================================

/**
 * Re-export IUser from interfaces
 */
export type { IUser };

/**
 * User registration data
 */
export interface UserRegistrationData {
  email: string;
  password: string;
  displayName: string;
}

/**
 * User login credentials
 */
export interface UserLoginCredentials {
  email: string;
  password: string;
}

/**
 * User profile update data
 */
export interface UserProfileUpdateData {
  displayName?: string;
  photoURL?: string;
  bio?: string;
  phoneNumber?: string;
}

/**
 * User password change data
 */
export interface UserPasswordChangeData {
  currentPassword: string;
  newPassword: string;
}

// ============================================
// MEETING TYPES
// ============================================

/**
 * Meeting object
 */
export interface Meeting {
  id: string;
  name: string;
  description?: string;
  hostId: string;
  hostName: string;
  scheduledAt?: Date | string;
  duration?: number; // in minutes
  isActive: boolean;
  isRecording: boolean;
  participants: MeetingParticipant[];
  roomId: string;
  createdAt: Date | string;
  updatedAt: Date | string;
}

/**
 * Meeting participant
 */
export interface MeetingParticipant {
  userId: string;
  displayName: string;
  photoURL?: string;
  joinedAt: Date | string;
  isHost: boolean;
  isMuted: boolean;
  isVideoOff: boolean;
}

/**
 * Meeting creation data
 */
export interface MeetingCreateData {
  name: string;
  description?: string;
  scheduledAt?: Date | string;
  duration?: number;
  isPrivate?: boolean;
}

/**
 * Meeting update data
 */
export interface MeetingUpdateData {
  name?: string;
  description?: string;
  scheduledAt?: Date | string;
  duration?: number;
  isActive?: boolean;
  isRecording?: boolean;
}

/**
 * Meeting join request
 */
export interface MeetingJoinRequest {
  roomId: string;
  displayName: string;
  userId?: string;
}

// ============================================
// CHAT TYPES
// ============================================

/**
 * Chat message
 */
export interface ChatMessage {
  id: string;
  meetingId: string;
  userId: string;
  userName: string;
  userPhotoURL?: string;
  message: string;
  timestamp: Date | string;
  isEdited?: boolean;
  replyTo?: string;
}

/**
 * Chat message send data
 */
export interface ChatMessageSendData {
  meetingId: string;
  message: string;
  replyTo?: string;
}

// ============================================
// AI TYPES
// ============================================

/**
 * Meeting summary generated by AI
 */
export interface MeetingSummary {
  id: string;
  meetingId: string;
  summary: string;
  keyPoints: string[];
  actionItems: string[];
  participants: string[];
  duration: number;
  generatedAt: Date | string;
}

/**
 * AI summary request
 */
export interface AISummaryRequest {
  meetingId: string;
  includeChat?: boolean;
  includeTranscript?: boolean;
}

// ============================================
// ANALYTICS TYPES
// ============================================

/**
 * User analytics data
 */
export interface UserAnalytics {
  userId: string;
  totalMeetings: number;
  totalMinutes: number;
  averageMeetingDuration: number;
  meetingsHosted: number;
  meetingsAttended: number;
  mostActiveDays: string[];
  lastActive: Date | string;
}

/**
 * Meeting analytics data
 */
export interface MeetingAnalytics {
  meetingId: string;
  totalParticipants: number;
  averageParticipants: number;
  duration: number;
  chatMessageCount: number;
  peakParticipants: number;
  participantJoinTimes: Record<string, string>;
  participantLeaveTimes: Record<string, string>;
}

/**
 * Analytics time range filter
 */
export interface AnalyticsTimeRange {
  startDate: Date | string;
  endDate: Date | string;
}

// ============================================
// RECORDING TYPES
// ============================================

/**
 * Meeting recording
 */
export interface MeetingRecording {
  id: string;
  meetingId: string;
  url: string;
  duration: number;
  size: number;
  format: string;
  startedAt: Date | string;
  endedAt: Date | string;
  createdAt: Date | string;
}

/**
 * Recording start request
 */
export interface RecordingStartRequest {
  meetingId: string;
  quality?: 'low' | 'medium' | 'high';
  includeAudio?: boolean;
  includeVideo?: boolean;
}

// ============================================
// NOTIFICATION TYPES
// ============================================

/**
 * Notification object
 */
export interface Notification {
  id: string;
  userId: string;
  type: 'meeting_invite' | 'meeting_start' | 'meeting_end' | 'message' | 'system';
  title: string;
  message: string;
  isRead: boolean;
  actionUrl?: string;
  createdAt: Date | string;
}

// ============================================
// WEBSOCKET TYPES
// ============================================

/**
 * WebSocket message types
 */
export type WebSocketMessageType = 
  | 'join'
  | 'leave'
  | 'chat'
  | 'participant_update'
  | 'meeting_update'
  | 'recording_start'
  | 'recording_stop'
  | 'error';

/**
 * WebSocket message
 */
export interface WebSocketMessage {
  type: WebSocketMessageType;
  payload: any;
  timestamp: Date | string;
}

// ============================================
// FORM TYPES
// ============================================

/**
 * Generic form field error
 */
export interface FormFieldError {
  field: string;
  message: string;
}

/**
 * Form validation result
 */
export interface FormValidationResult {
  isValid: boolean;
  errors: FormFieldError[];
}

// ============================================
// UTILITY TYPES
// ============================================

/**
 * Async operation state
 */
export interface AsyncState<T = any> {
  loading: boolean;
  error: string | null;
  data: T | null;
}

/**
 * Option type for select inputs
 */
export interface SelectOption<T = string> {
  label: string;
  value: T;
  disabled?: boolean;
}

/**
 * Make all properties of T optional recursively
 */
export type DeepPartial<T> = {
  [P in keyof T]?: T[P] extends object ? DeepPartial<T[P]> : T[P];
};

/**
 * Extract keys from object type T where value is of type V
 */
export type KeysOfType<T, V> = {
  [K in keyof T]: T[K] extends V ? K : never;
}[keyof T];
